djangoapp/blog/urls.py
from blog import views
from django.urls import path

app_name = "blog"
urlpatterns = [
    path('', views.PostListView.as_view(), name="index"),
    path('page/<slug:slug>/', views.PageDetailView.as_view(), name="page"),
    path('post/<slug:slug>/', views.PostDetailView.as_view(), name="post"),
    path(
        'created_by/<int:author_id>/', views.CreatedByListView.as_view(),
        name="author"),
    path('category/<slug:slug>/', views.CategoryListView.as_view(),
         name="category"),
    path('tag/<slug:slug>/', views.TagListView.as_view(), name="tag"),
    path('search/', views.SearchListView.as_view(), name="search"),
]

djangoapp/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path("", include("blog.urls"))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
    

djangoapp/blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django_summernote.models import AbstractAttachment
from utils import image
from utils.rands import random_slugify

# Create your models here.


class PostAttachment(AbstractAttachment):
    def save(self, *args, **kwargs):
        if not self.name:
            self.name = self.file.name
        current_file_name = str(self.file.name)
        super().save(*args, **kwargs)
        file_changed = False

        if self.file:
            file_changed = current_file_name != self.file.name

        if file_changed:
            image.resize_image(self.file, 900, True, 70)


class Tag(models.Model):
    class Meta:
        verbose_name = ("Tag")
        verbose_name_plural = ("Tags")

    name = models.CharField(("Name"), max_length=255)
    slug = models.SlugField(
        unique=True,
        default=None,
        null=True,
        blank=True,
        max_length=255
    )

    def __str__(self):
        return str(self.name)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = random_slugify(self.name, 5)
        return super().save(*args, **kwargs)


class Category(models.Model):
    class Meta:
        verbose_name = ("Category")
        verbose_name_plural = ("Categories")

    name = models.CharField(("Name"), max_length=255)
    slug = models.SlugField(
        unique=True,
        default=None,
        null=True,
        blank=True,
        max_length=255
    )

    def __str__(self):
        return str(self.name)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = random_slugify(self.name, 5)
        return super().save(*args, **kwargs)


class Page(models.Model):
    class Meta:
        verbose_name = ("Page")
        verbose_name_plural = ("Pages")

    title = models.CharField(("title"), max_length=50)
    slug = models.SlugField(
        unique=True,
        default=None,
        null=False,
        blank=True,
        max_length=255
    )
    is_published = models.BooleanField(("Publicado"),
                                       default=False,
                                       help_text="Este campo torna a página \
                                       pública")
    content = models.TextField()

    def __str__(self):
        return str(self.title)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = random_slugify(self.title, 5)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("blog:page", kwargs={"slug": self.slug})


class PostManager(models.Manager):
    def get_published(self):
        return self.filter(is_published=True).order_by("-created_at")


class Post(models.Model):
    class Meta:
        verbose_name = ("Post")
        verbose_name_plural = ("Posts")

    title = models.CharField(max_length=65)
    slug = models.SlugField(
        unique=True,
        default=None,
        null=False,
        blank=True,
        max_length=255
    )
    excerpt = models.CharField(max_length=150)
    is_published = models.BooleanField(("Publicado"),
                                       default=False,
                                       help_text="Este campo torna o post \
                                       pública")
    content = models.TextField()
    cover = models.ImageField(upload_to="posts/", blank=True, default="")
    cover_in_post_content = models.BooleanField(default=True,
                                                help_text="Exibe a capa dentro\
                                                do post")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    created_by = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL,
                                   blank=True, null=True,
                                   related_name="post_created_by")
    updated_by = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL,
                                   null=True,
                                   related_name="post_updated_by")
    category = models.ForeignKey(Category, verbose_name=("categories"),
                                 on_delete=models.SET_NULL,
                                 null=True, blank=True,
                                 default=None)
    tag = models.ManyToManyField(Tag, blank=True, default='',
                                 related_name="tag_set")
    objects = PostManager()

    def __str__(self):
        return str(self.title)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = random_slugify(self.title, 5)
        current_cover_name = str(self.cover.name)
        super().save(*args, **kwargs)
        cover_changed = False

        if self.cover:
            cover_changed = current_cover_name != self.cover.name

        if cover_changed:
            image.resize_image(self.cover, 900, True, 70)

    def get_absolute_url(self):
        return reverse("blog:post", kwargs={"slug": self.slug})

djangoapp/blog/views.py
from blog.models import Category, Page, Post, Tag
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import Http404
from django.shortcuts import redirect
from django.views.generic import DetailView, ListView

POSTS_PER_PAGE = 9


# Create your views here.
class PostListView(ListView):
    model = Post
    template_name = "blog/pages/index.html"
    context_object_name = "posts"
    ordering = ("-created_at")
    queryset = Post.objects.get_published()
    paginate_by = POSTS_PER_PAGE

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "Home - "
        return context


class CreatedByListView(PostListView):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._temp_context = {}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author_id = self.kwargs.get("author_id")
        print(f"\n{author_id}")
        user = self._temp_context["user"]

        user_name = user.username
        context.update({
            "page_title": f'posts de {user_name} - '
        })

        return context

    def get_queryset(self):
        qs = super().get_queryset()
        author_id = self._temp_context["author_id"]
        qs = qs.filter(created_by__pk=author_id)
        return qs

    def get(self, request, *args, **kwargs):
        author_id = self.kwargs.get("author_id")
        user = User.objects.filter(pk=author_id).first()

        if user is None:
            raise Http404()

        self._temp_context.update(
            {
                "author_id": author_id,
                "user": user
                }
        )

        return super().get(request, *args, **kwargs)


class CategoryListView(PostListView):
    allow_empty = False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category_name = self.kwargs.get("category").name
        context.update(
            {"page_title": f"{category_name} - "}
        )
        return context

    def get(self, request, *args, **kwargs):
        category_object = Category.objects\
            .filter(slug=self.kwargs.get("slug")).first()

        self.kwargs.update({"category": category_object})
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return super().get_queryset()\
            .filter(category__slug=self.kwargs.get("slug"))


class TagListView(PostListView):
    allow_empty = False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tag_name = self.kwargs.get("tag").name
        context.update(
            {"page_title": f"{tag_name} - "}
        )
        return context

    def get(self, request, *args, **kwargs):
        tag_object = Tag.objects\
            .filter(slug=self.kwargs.get("slug")).first()

        self.kwargs.update({"tag": tag_object})
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return super().get_queryset()\
            .filter(tag__slug=self.kwargs.get("slug"))


class SearchListView(PostListView):
    def setup(self, request, *args, **kwargs) -> None:
        self._search_value = request.GET["search"].strip()
        return super().setup(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_value = self._search_value
        context.update(
            {
                "page_title": f"{search_value} - ",
                "search_value": search_value
                }
        )
        return context

    def get_queryset(self):
        search_value = self._search_value
        return super().get_queryset().filter(
            Q(title__icontains=search_value) |
            Q(excerpt__icontains=search_value) |
            Q(content__icontains=search_value)
        )

    def get(self, request, *args, **kwargs):
        if self._search_value == "":
            return redirect("blog:index")

        return super().get(request, *args, **kwargs)


class PageDetailView(DetailView):
    model = Page
    template_name = "blog/pages/page.html"
    slug_field = "slug"
    context_object_name = "page"
    NOT_FOUND_ERR_MSG = "Não possivel encontrar a página, \
tente novamente mais tarde"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page_title = context["page"].title
        context.update({
            "page_title": f"{page_title} - "
        })
        return context

    def get_object(self, queryset=None):
        try:
            obj = super().get_object(queryset)
        except Http404:
            # Sobrescrevendo mensagem de erro pela customizada da classe.
            raise Http404(self.NOT_FOUND_ERR_MSG)
        return obj

    def get(self, request, *args, **kwargs):
        page_obj = self.get_object()
        if not (page_obj.is_published or request.user.is_staff):
            raise Http404(self.NOT_FOUND_ERR_MSG)
        return super().get(request, *args, **kwargs)


class PostDetailView(DetailView):
    model = Post
    template_name = "blog/pages/post.html"
    context_object_name = "post"
    NOT_FOUND_ERR_MSG = "Não possivel encontrar o post, \
tente novamente mais tarde"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page_title = context["post"].title
        context.update({
            "page_title": f"{page_title} - "
        })
        return context

    def get_object(self, queryset=None):
        try:
            obj = super().get_object(queryset)
        except Http404:
            # Sobrescrevendo mensagem de erro pela customizada da classe.
            raise Http404(self.NOT_FOUND_ERR_MSG)
        return obj

    def get(self, request, *args, **kwargs):
        page_obj = self.get_object()
        if not (page_obj.is_published or request.user.is_staff):
            raise Http404(self.NOT_FOUND_ERR_MSG)
        return super().get(request, *args, **kwargs)

djangoapp/blog/templates/blog/pages/index.html
{% extends 'blog/base.html' %}

{% block content %}
  <main class="main-content section-wrapper">
    <div class="section-content-wide">
      <div class="section-gap">

        {% if posts %}
        <div class="card-grid">
          {% for post in posts %}
            {% include 'blog/partials/_post-card.html'%}
          {% endfor %}
        </div>
        {% else %}
        <div class="not-found center">
          <h1>Nada encontrado</h1>
          <p>
            Nada foi encontrado nesse link, clique em outro link ou vá para a 
            <a href="{% url 'blog:index' %}">home</a>
          </p>
        {% endif %}
        
      </div>
    </div>
  </main>
{% endblock content %}

djangoapp/blog/templates/blog/pages/page.html
{% extends 'blog/base.html' %}

{% block content %}
  <main class="main-content section-wrapper">
    <div class="section-content-narrow">
      <div class="section-gap">
        <h1 class="center">{{ page.title }}</h1>
        <p>{{ page.content | safe}}</p>
      </div>
    </div>
  </main>
{% endblock content %}

djangoapp/blog/templates/blog/pages/post.html
{% extends 'blog/base.html' %} 

{% block additional_head %}
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/codemirror.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/theme/dracula.min.css">

  <script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/codemirror.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/python/python.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/php/php.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/clike/clike.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/javascript/javascript.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/htmlmixed/htmlmixed.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/css/css.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/xml/xml.min.js"></script>
{% endblock additional_head %}

{% block content %}
<main class="main-content single-post section-wrapper">
  <div class="single-post-content section-content-narrow">
    <div class="single-post-gap section-gap">
      
      {% if post.cover_in_post_content and post.cover %}
        <div class="single-post-cover pb-base">
          <img loading="lazy" src="{{ post.cover.url }}" alt="Change me">
        </div>
      {% endif %}

      <h2 class="single-post-title pb-base center">
        {{ post.title }}
      </h2>

      <div class="post-meta pb-base">
        <div class="post-meta-item">
          <a class="post-meta-link" href="{% url 'blog:author' post.created_by.id %}">
            <i class="fa-solid fa-user"></i>
            <span>
              {{ post.created_by }}
            </span>
          </a>
        </div>
        <div class="post-meta-item">
          <span class="post-meta-link">
            <i class="fa-solid fa-calendar-days"></i>
            <span>
              {{ post.created_at | date:'d/m/Y \à\s H:i'}}
            </span>
          </span>
        </div>
        {% if post.category %}
          <div class="post-meta-item">
            <a class="post-meta-link" href="{% url 'blog:category' post.category.slug %}">
              <i class="fa-solid fa-tag"></i>
              <span>
                {{ post.category.name }}
              </span>
            </a>
          </div>
        {% endif %}
      </div>

      <p class="single-post-excerpt pb-base">
        {{ post.excerpt | safe }}
      </p>

      <div class="separator"></div>

      <div class="single-post-content">
        {{post.content | safe}}
        
        
        
          <div class="post-tags">
            {% if post.tag.all.exists %}
            <span>Tags: </span>

            
            {% for tag in post.tag.all  %}
              <a class="post-tag-link" href="{% url 'blog:tag' tag.slug %}">
                <i class="fa-solid fa-link"></i>
                <span>{{ tag.name }}</span>
              </a>
            {% endfor %}
            {% endif %}
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock content %}